from typing import List, Tuple

class MetalKMeans:
    def __init__(self, n_clusters: int, max_iterations: int = 100, tolerance: float = 1e-4, seed: int = 42) -> None: ...
    def fit(self, data: List[float], n: int, d: int) -> None: ...
    def predict(self, data: List[float], n: int, d: int) -> List[int]: ...
    @property
    def centroids(self) -> List[float]: ...
    @property
    def labels(self) -> List[int]: ...
    @property
    def inertia(self) -> float: ...
    @property
    def n_iter(self) -> int: ...

def metal_kmeans_fit(
    data: List[float],
    n: int,
    d: int,
    n_clusters: int,
    max_iterations: int = 100,
    tolerance: float = 1e-4,
    seed: int = 42,
) -> Tuple[List[int], List[float], int, float]: ...
