from typing import List, Tuple

class MetalKMeans:
    def __init__(self, n_clusters: int, max_iterations: int = 100, tolerance: float = 1e-4, seed: int = 42) -> None: ...
    def fit(self, data: List[float], n: int, d: int) -> None: ...
    def predict(self, data: List[float], n: int, d: int) -> List[int]: ...
    def fit_bytes(self, data: bytes, n: int, d: int) -> None: ...
    def predict_bytes(self, data: bytes, n: int, d: int) -> List[int]: ...
    @property
    def centroids(self) -> List[float]: ...
    @property
    def labels(self) -> List[int]: ...
    @property
    def inertia(self) -> float: ...
    @property
    def n_iter(self) -> int: ...

def metal_kmeans_fit(
    data: List[float],
    n: int,
    d: int,
    n_clusters: int,
    max_iterations: int = 100,
    tolerance: float = 1e-4,
    seed: int = 42,
) -> Tuple[List[int], List[float], int, float]: ...

def metal_kmeans_fit_bytes(
    data: bytes,
    n: int,
    d: int,
    n_clusters: int,
    max_iterations: int = 100,
    tolerance: float = 1e-4,
    seed: int = 42,
) -> Tuple[List[int], List[float], int, float]: ...

class MetalKNeighbors:
    def __init__(self, n_neighbors: int = 5) -> None: ...
    def fit(self, data: List[float], n: int, d: int) -> None: ...
    def kneighbors(self, queries: List[float], nq: int) -> Tuple[List[float], List[int]]: ...
    def fit_bytes(self, data: bytes, n: int, d: int) -> None: ...
    def kneighbors_bytes(self, queries: bytes, nq: int) -> Tuple[List[float], List[int]]: ...

def metal_kneighbors(
    corpus: List[float],
    n_corpus: int,
    d: int,
    queries: List[float],
    n_queries: int,
    n_neighbors: int = 5,
) -> Tuple[List[float], List[int]]: ...

def metal_kneighbors_bytes(
    corpus: bytes,
    n_corpus: int,
    d: int,
    queries: bytes,
    n_queries: int,
    n_neighbors: int = 5,
) -> Tuple[List[float], List[int]]: ...

class MetalLDA:
    def __init__(self, n_components: int) -> None: ...
    def fit(self, data: List[float], labels: List[float], n: int, d: int) -> None: ...
    def transform(self, data: List[float], n: int, d: int) -> List[float]: ...
    def fit_transform(self, data: List[float], labels: List[float], n: int, d: int) -> List[float]: ...
    def predict(self, data: List[float], n: int, d: int) -> List[int]: ...
    def score(self, data: List[float], labels: List[float], n: int, d: int) -> float: ...
    def fit_bytes(self, data: bytes, labels: bytes, n: int, d: int) -> None: ...
    def transform_bytes(self, data: bytes, n: int, d: int) -> List[float]: ...
    def fit_transform_bytes(self, data: bytes, labels: bytes, n: int, d: int) -> List[float]: ...
    def predict_bytes(self, data: bytes, n: int, d: int) -> List[int]: ...
    def score_bytes(self, data: bytes, labels: bytes, n: int, d: int) -> float: ...
    @property
    def scalings(self) -> List[float]: ...
    @property
    def coeffs(self) -> List[float]: ...
    @property
    def mean(self) -> List[float]: ...
    @property
    def eigenvalues(self) -> List[float]: ...
    @property
    def classes(self) -> List[float]: ...
    @property
    def class_counts(self) -> List[float]: ...
    @property
    def class_means(self) -> List[float]: ...
    @property
    def n_components(self) -> int: ...

def metal_lda_fit(
    data: List[float],
    labels: List[float],
    n: int,
    d: int,
    n_components: int,
) -> Tuple[List[float], List[float], List[float]]: ...

def metal_lda_fit_bytes(
    data: bytes,
    labels: bytes,
    n: int,
    d: int,
    n_components: int,
) -> Tuple[List[float], List[float], List[float]]: ...

class MetalPCA:
    def __init__(self, n_components: int) -> None: ...
    def fit(self, data: List[float], n: int, d: int) -> None: ...
    def transform(self, data: List[float], n: int, d: int) -> List[float]: ...
    def fit_transform(self, data: List[float], n: int, d: int) -> List[float]: ...
    def fit_bytes(self, data: bytes, n: int, d: int) -> None: ...
    def transform_bytes(self, data: bytes, n: int, d: int) -> List[float]: ...
    def fit_transform_bytes(self, data: bytes, n: int, d: int) -> List[float]: ...
    @property
    def components(self) -> List[float]: ...
    @property
    def explained_variance(self) -> List[float]: ...
    @property
    def explained_variance_ratio(self) -> List[float]: ...
    @property
    def singular_values(self) -> List[float]: ...
    @property
    def mean(self) -> List[float]: ...
    @property
    def noise_variance(self) -> float: ...

def metal_pca_fit(
    data: List[float],
    n: int,
    d: int,
    n_components: int,
) -> Tuple[List[float], List[float], List[float]]: ...

def metal_pca_fit_bytes(
    data: bytes,
    n: int,
    d: int,
    n_components: int,
) -> Tuple[List[float], List[float], List[float]]: ...

class MetalTSNE:
    def __init__(
        self,
        n_components: int = 2,
        perplexity: float = 30.0,
        learning_rate: float = 200.0,
        n_iter: int = 1000,
        early_exaggeration: float = 12.0,
        exaggeration_iter: int = 250,
        momentum: float = 0.8,
        seed: int = 42,
        min_grad_norm: float = 1e-7,
    ) -> None: ...
    def fit(self, data: List[float], n: int, d: int) -> None: ...
    def fit_bytes(self, data: bytes, n: int, d: int) -> None: ...
    @property
    def embedding(self) -> List[float]: ...
    @property
    def n_iter(self) -> int: ...
    @property
    def kl_divergence(self) -> float: ...

def metal_tsne_fit(
    data: List[float],
    n: int,
    d: int,
    n_components: int = 2,
    perplexity: float = 30.0,
    learning_rate: float = 200.0,
    n_iter: int = 1000,
    early_exaggeration: float = 12.0,
    exaggeration_iter: int = 250,
    momentum: float = 0.8,
    seed: int = 42,
    min_grad_norm: float = 1e-7,
) -> Tuple[List[float], int, float]: ...

def metal_tsne_fit_bytes(
    data: bytes,
    n: int,
    d: int,
    n_components: int = 2,
    perplexity: float = 30.0,
    learning_rate: float = 200.0,
    n_iter: int = 1000,
    early_exaggeration: float = 12.0,
    exaggeration_iter: int = 250,
    momentum: float = 0.8,
    seed: int = 42,
    min_grad_norm: float = 1e-7,
) -> Tuple[List[float], int, float]: ...

class MetalLogisticRegression:
    def __init__(
        self,
        c: float = 1.0,
        learning_rate: float = 0.01,
        momentum: float = 0.9,
        max_epochs: int = 100,
        batch_size: int = 256,
        tol: float = 1e-4,
        seed: int = 42,
    ) -> None: ...
    def fit(self, data: List[float], y: List[float], n: int, d: int) -> None: ...
    def predict(self, data: List[float], n: int, d: int) -> List[float]: ...
    def predict_proba(self, data: List[float], n: int, d: int) -> List[float]: ...
    def score(self, data: List[float], y: List[float], n: int, d: int) -> float: ...
    def fit_bytes(self, data: bytes, y: bytes, n: int, d: int) -> None: ...
    def predict_bytes(self, data: bytes, n: int, d: int) -> List[float]: ...
    def predict_proba_bytes(self, data: bytes, n: int, d: int) -> List[float]: ...
    def score_bytes(self, data: bytes, y: bytes, n: int, d: int) -> float: ...
    @property
    def weights(self) -> List[float]: ...
    @property
    def bias(self) -> float: ...
    @property
    def coef_(self) -> List[float]: ...
    @property
    def intercept_(self) -> float: ...
    @property
    def n_epochs(self) -> int: ...
    @property
    def final_loss(self) -> float: ...

def metal_logistic_regression_fit(
    data: List[float],
    y: List[float],
    n: int,
    d: int,
    c: float = 1.0,
    learning_rate: float = 0.01,
    momentum: float = 0.9,
    max_epochs: int = 100,
    batch_size: int = 256,
    tol: float = 1e-4,
    seed: int = 42,
) -> Tuple[List[float], float, int, float]: ...

def metal_logistic_regression_fit_bytes(
    data: bytes,
    y: bytes,
    n: int,
    d: int,
    c: float = 1.0,
    learning_rate: float = 0.01,
    momentum: float = 0.9,
    max_epochs: int = 100,
    batch_size: int = 256,
    tol: float = 1e-4,
    seed: int = 42,
) -> Tuple[List[float], float, int, float]: ...

class MetalSVC:
    def __init__(
        self,
        kernel: str = "rbf",
        gamma: float = 0.0,
        degree: float = 3.0,
        coef0: float = 0.0,
        c: float = 1.0,
        tolerance: float = 1e-3,
        max_iter: int = 200,
        seed: int = 42,
    ) -> None: ...
    def fit(self, data: List[float], y: List[float], n: int, d: int) -> None: ...
    def predict(self, data: List[float], n: int, d: int) -> List[float]: ...
    def decision_function(self, data: List[float], n: int, d: int) -> List[float]: ...
    def score(self, data: List[float], y: List[float], n: int, d: int) -> float: ...
    def fit_bytes(self, data: bytes, y: bytes, n: int, d: int) -> None: ...
    def predict_bytes(self, data: bytes, n: int, d: int) -> List[float]: ...
    def decision_function_bytes(self, data: bytes, n: int, d: int) -> List[float]: ...
    def score_bytes(self, data: bytes, y: bytes, n: int, d: int) -> float: ...
    @property
    def classes(self) -> List[float]: ...
    @property
    def intercept_(self) -> List[float]: ...
    @property
    def n_support(self) -> List[int]: ...
    @property
    def dual_coef_(self) -> List[float]: ...
    @property
    def support_vectors_(self) -> List[float]: ...
    @property
    def gamma_(self) -> float: ...
    @property
    def n_iter(self) -> List[int]: ...

def metal_svc_fit(
    data: List[float],
    y: List[float],
    n: int,
    d: int,
    kernel: str = "linear",
    gamma: float = 20.0,
    degree: float = 3.0,
    coef0: float = 0.0,
    c: float = 1.0,
    tolerance: float = 1e-4,
    max_iter: int = 25,
    seed: int = 42,
) -> Tuple[List[float], List[float], List[float], List[float], int, float, List[int]]: ...

def metal_svc_fit_bytes(
    data: bytes,
    y: bytes,
    n: int,
    d: int,
    kernel: str = "linear",
    gamma: float = 20.0,
    degree: float = 3.0,
    coef0: float = 0.0,
    c: float = 1.0,
    tolerance: float = 1e-4,
    max_iter: int = 25,
    seed: int = 42,
) -> Tuple[List[float], List[float], List[float], List[float], int, float, List[int]]: ...
